### ISSUE TITLE
errors during install

### ISSUE THREAD

**Issue by piotr-placzek** [luxdvie/WS2812Controller#2]
I will not write too much. You have to see npm install log. There are many errors in code...
```
pi@raspberrypi:~/WS2812Controller $ npm install


> rpi-ws281x-native@0.9.0 install /home/pi/WS2812Controller/node_modules/rpi-ws281x-native
> node-gyp rebuild

make: Entering directory '/home/pi/WS2812Controller/node_modules/rpi-ws281x-native/build'
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/ws2811.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/pwm.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/dma.o
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/mailbox.o
../src/rpi_ws281x/mailbox.c: In function ‘mbox_open’:
../src/rpi_ws281x/mailbox.c:289:37: warning: implicit declaration of function ‘makedev’ [-Wimplicit-function-declaration]
   if (mknod(filename, S_IFCHR|0600, makedev(100, 0)) < 0) {
                                     ^~~~~~~
  CC(target) Release/obj.target/rpi_libws2811/src/rpi_ws281x/board_info.o
  AR(target) Release/obj.target/rpi_libws2811.a
  COPY Release/rpi_libws2811.a
  CXX(target) Release/obj.target/rpi_ws281x/src/rpi-ws281x.o
../src/rpi-ws281x.cc: In function ‘void render(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/rpi-ws281x.cc:43:44: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object> buffer = info[0]->ToObject();
                                            ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc: In function ‘void init(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/rpi-ws281x.cc:87:52: error: no matching function for call to ‘v8::Value::Int32Value()’
   ledstring.channel[0].count = info[0]->Int32Value();
                                                    ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc:91:46: error: no matching function for call to ‘v8::Value::ToObject()’
     Local<Object> config = info[1]->ToObject();
                                              ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:101:43: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       ledstring.freq = config->Get(symFreq)->Uint32Value();
                                           ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:101:58: error: no matching function for call to ‘v8::Value::Uint32Value()’
       ledstring.freq = config->Get(symFreq)->Uint32Value();
                                                          ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2611:41: note: candidate: ‘v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2611:41: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc:105:47: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       ledstring.dmanum = config->Get(symDmaNum)->Int32Value();
                                               ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:105:61: error: no matching function for call to ‘v8::Value::Int32Value()’
       ledstring.dmanum = config->Get(symDmaNum)->Int32Value();
                                                             ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc:109:60: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       ledstring.channel[0].gpionum = config->Get(symGpioPin)->Int32Value();
                                                            ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:109:74: error: no matching function for call to ‘v8::Value::Int32Value()’
       ledstring.channel[0].gpionum = config->Get(symGpioPin)->Int32Value();
                                                                          ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc:113:58: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       ledstring.channel[0].invert = config->Get(symInvert)->Int32Value();
                                                          ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:113:72: error: no matching function for call to ‘v8::Value::Int32Value()’
       ledstring.channel[0].invert = config->Get(symInvert)->Int32Value();
                                                                        ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc:117:66: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       ledstring.channel[0].brightness = config->Get(symBrightness)->Int32Value();
                                                                  ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/rpi-ws281x.cc:117:80: error: no matching function for call to ‘v8::Value::Int32Value()’
       ledstring.channel[0].brightness = config->Get(symBrightness)->Int32Value();
                                                                                ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc: In function ‘void setBrightness(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/rpi-ws281x.cc:144:57: error: no matching function for call to ‘v8::Value::Int32Value()’
   ledstring.channel[0].brightness = info[0]->Int32Value();
                                                         ^
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../src/rpi-ws281x.cc: At global scope:
../src/rpi-ws281x.cc:168:17: error: variable or field ‘initialize’ declared void
 void initialize(Handle<Object> exports) {
                 ^~~~~~
../src/rpi-ws281x.cc:168:17: error: ‘Handle’ was not declared in this scope
../src/rpi-ws281x.cc:168:17: note: suggested alternative: ‘rand_r’
 void initialize(Handle<Object> exports) {
                 ^~~~~~
                 rand_r
../src/rpi-ws281x.cc:168:30: error: expected primary-expression before ‘>’ token
 void initialize(Handle<Object> exports) {
                              ^
../src/rpi-ws281x.cc:168:32: error: ‘exports’ was not declared in this scope
 void initialize(Handle<Object> exports) {
                                ^~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
../src/rpi-ws281x.cc:175:25: error: ‘initialize’ was not declared in this scope
 NODE_MODULE(rpi_ws281x, initialize)
                         ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/rpi-ws281x.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(rpi_ws281x, initialize)
 ^~~~~~~~~~~
../src/rpi-ws281x.cc:175:25: note: suggested alternative: ‘initstate’
 NODE_MODULE(rpi_ws281x, initialize)
                         ^~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/rpi-ws281x.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(rpi_ws281x, initialize)
 ^~~~~~~~~~~
In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/rpi-ws281x.cc:1:
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pi/.cache/node-gyp/12.14.1/include/node/node_object_wrap.h:84:78:   required from here
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [rpi_ws281x.target.mk:110: Release/obj.target/rpi_ws281x/src/rpi-ws281x.o] Error 1
make: Leaving directory '/home/pi/WS2812Controller/node_modules/rpi-ws281x-native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.83-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/WS2812Controller/node_modules/rpi-ws281x-native
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpi-ws281x-native@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpi-ws281x-native@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-02-14T11_10_38_162Z-debug.log
```

**Comment by luxdvie** [comment]
This looks to be a problem after doing `npm install` to install the dependencies. I ran into similar issues on my Raspberry Pi Zero. In steps 3, 4, and 5 [of the README](https://github.com/luxdvie/WS2812Controller#raspberry-pi-setup), I mention that I ran into similar problems. Can you give these steps a try?

1. add following lines to ~/.bashrc after installing npm:
```
 npm set prefix ~/.npm
 PATH="$HOME/.npm/bin:$PATH"
 PATH="./node_modules/.bin:$PATH"
```
2. run `source ~/.bashrc`
3. delete the `package-lock.json` file and `node_modules` directory
4. run `npm install` again. Avoid using `sudo`

**Comment by piotr-placzek** [comment]
Sure, I did it. 

As I thought, it doesn't change anything. I have correctly set env vars.

I wrote few js apps that works well at my rpi zero, and rpi 3b.

**Comment by piotr-placzek** [comment]
It must be added that I am trying to run your application on a clean raspberry system.

**Comment by piotr-placzek** [comment]
OK, I got it! There is a problem with `rpi-ws281x-native`.
I tried to `npm install rpi-ws281x-native` in new project, and I got this same errors.

I just clone and install `rpi-ws281x-native` from [source](https://github.com/beyondscreen/node-rpi-ws281x-native#setup),
and next I `npm install ../node-rpi-ws281x-native/` inside your app. This is the **solution**, for me.

You suggest avoiding using sudo, but rpi-ws281x-native requires being run with root-privileges.
```
pi@raspberrypi:~/WS2812Controller $ node app.js 
[rpi-ws281x-native] This module requires being run with root-privileges. A non-functional stub of the interface will be returned.
***************************
 WS2812 CONTROLLER STARTUP 
 Web Server listening at the location below, or by host name and port. 
 http://192.168.0.199:8080
***************************
Going rainbow mode.
^C
pi@raspberrypi:~/WS2812Controller $ sudo node app.js 
***************************
 WS2812 CONTROLLER STARTUP 
 Web Server listening at the location below, or by host name and port. 
 http://192.168.0.199:8080
***************************
Going rainbow mode.
```

**Comment by luxdvie** [comment]
Ah, thanks for the update! Glad you were able to get it running.

Yep, unfortunately, that library requires that the node program be run as sudo. My recommendation was to avoid using `sudo npm install`, to avoid permissions issues in the node_modules directory. Looks like you didn't need that.
